learning/djangoLearning/PracticalDjangoProjects2ndEdition/Version1.2/simplecms/src/simplecms/urls.py
#coding=utf8
import settings
from django.conf.urls.defaults import *
from simplecms import views
from simplecms.search import views as sv
from simplecms.coltrane.feeds import CategoryFeed, LatestEntriesFeed 

from django.contrib import admin
admin.autodiscover()

feeds = {'entries': LatestEntriesFeed,
         'categories': CategoryFeed}

urlpatterns = patterns('',
    # Example:
    # (r'^simplecms/', include('simplecms.foo.urls')),
    
    (r'^feeds/(?P<url>.*)/$',
     'django.contrib.syndication.views.feed',
     { 'feed_dict': feeds }),
     
    (r'^$', views.index),
    (r'^search/$', sv.search),
    
    (r'^weblog/categories/', include('simplecms.coltrane.urls.categories')),
    (r'^weblog/links/', include('simplecms.coltrane.urls.links')),
    (r'^weblog/tags/', include('simplecms.coltrane.urls.tags')),
    (r'^weblog/', include('simplecms.coltrane.urls.entries')),
    
    (r'^snippets/', include('simplecms.cab.urls.snippets')),
    (r'^snippets/tags/', include('simplecms.cab.urls.tags')),
    (r'^snippets/languages/', include('simplecms.cab.urls.languages')),
    (r'^snippets/bookmarks/', include('simplecms.cab.urls.bookmarks')),
    (r'^popular/', include('simplecms.cab.urls.popular')),
    
    (r'^signup/', 'simplecms.views.signup'),

    (r'^comments/', include('django.contrib.comments.urls')),

    # serve static medias
    (r'^media/(?P<path>.*)$',
        'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT}),

    (r'^images/(?P<path>.*)$',
        'django.views.static.serve',
        {'document_root': settings.STATIC_IMAGE}),

    (r'^css/(?P<path>.*)$',
        'django.views.static.serve',
        {'document_root': settings.STATIC_CSS}),

    (r'^js/(?P<path>.*)$',
        'django.views.static.serve',
        {'document_root': settings.STATIC_JS}),

    (r'^upload/(?P<path>.*)$',
        'django.views.static.serve',
        {'document_root': settings.STATIC_UPLOAD}),

    # tiny_mce.js
    (r'^tiny_mce/(?P<path>.*)$', 'django.views.static.serve',
        { 'document_root': settings.STATIC_JS + '/tinymce/jscripts/tiny_mce'}),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs'
    # to INSTALLED_APPS to enable admin documentation:
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),


    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
    # flatpages相关
    (r'', include('django.contrib.flatpages.urls')),
)

learning/djangoLearning/PracticalDjangoProjects2ndEdition/Version1.2/simplecms/src/simplecms/cab/models.py
#coding=utf8
import datetime

from django.db import models
from pygments import formatters, highlight, lexers
from markdown import markdown
from tagging.fields import TagField
from django.contrib.auth.models import User
from simplecms.cab import managers

class Language(models.Model):
    name = models.CharField('名称', max_length = 100)
    slug = models.SlugField(unique = True)
    language_code = models.CharField('语言代码', max_length = 50)
    mime_type = models.CharField('mime类型', max_length = 100)

    class Meta:
        ordering = ['name']
        verbose_name = '语言'
        verbose_name_plural = '语言'
        
    def __unicode__(self):
        return self.name
    
    def clean(self):
        self.name = self.name.strip()
        self.slug = self.slug.strip()
        self.language_code = self.language_code.strip()
        self.mime_type = self.mime_type.strip()

    def get_absolute_url(self):
        return ('cab_language_detail', (), {'slug': self.slug})
    get_absolute_url = models.permalink(get_absolute_url)

    def get_lexer(self):
        return lexers.get_lexer_by_name(self.language_code)

    objects = managers.LanguageManager()

class Snippet(models.Model):
    title = models.CharField('标题', max_length = 255)
    language = models.ForeignKey(Language)
    author = models.ForeignKey(User)
    description = models.TextField('描述')
    description_html = models.TextField('描述html', editable = False)
    code = models.TextField('代码')
    highlighted_code = models.TextField('高亮代码', editable = False)
    tags = TagField('标签', help_text = '用空格隔开')
    pub_date = models.DateTimeField('发布日期', editable = False)
    updated_date = models.DateTimeField('更新日期', editable = False)

    class Meta:
        ordering = ['-pub_date']
        verbose_name = '片断'
        verbose_name_plural = '片断'

    def __unicode__(self):
        return self.title
    
    def clean(self):
        self.title = self.title.strip()
        self.description = self.description.strip()
        self.code = self.code.strip()
        self.tags = self.tags.strip()

    def save(self, force_insert = False, force_update = False):
        if not self.id:
            # 未创建就没有id
            self.pub_date = datetime.datetime.now()
        self.updated_date = datetime.datetime.now()
        self.description_html = markdown(self.description.strip())
        self.highlighted_code = self.highlight()
        super(Snippet, self).save(force_insert, force_update)

    def get_absolute_url(self):
        return ('cab_snippet_detail', (), {'object_id': self.id})
    get_absolute_url = models.permalink(get_absolute_url)

    def highlight(self):
        return highlight(self.code,
                         self.language.get_lexer(),
                         formatters.html.HtmlFormatter(linenos = True))

    objects = managers.SnippetManager()

class Bookmark(models.Model):
    snippet = models.ForeignKey(Snippet)
    user = models.ForeignKey(User, related_name = 'cab_bookmarks')
    date = models.DateTimeField(editable = False)
    
    class Meta:
        ordering = ['-date']
        verbose_name = '书签'
        verbose_name_plural = '书签'
        
    def __unicode__(self):
        return "%s bookmarked by %s" % (self.snippet, self.user)
    
    def save(self):
        if not self.id:
            self.date = datetime.datetime.now()
        super(Bookmark, self).save()

learning/djangoLearning/PracticalDjangoProjects2ndEdition/Version1.2/simplecms/src/simplecms/cab/views/bookmarks.py
#coding=utf8
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render_to_response
from django.contrib.auth.decorators import login_required
from django.views.generic.list_detail import object_list
from simplecms.cab.models import Bookmark, Snippet

def add_bookmark(request, snippet_id):
    snippet = get_object_or_404(Snippet, pk = snippet_id)
    try:
        Bookmark.objects.get(user__pk = request.user.id,
                             snippet__pk = snippet.id)
    except Bookmark.DoesNotExist:
        bookmark = Bookmark.objects.create(user = request.user,
                                           snippet = snippet)
    return HttpResponseRedirect(snippet.get_absolute_url())
add_bookmark = login_required(add_bookmark)

def delete_bookmark(request, snippet_id):
    if request.method == 'POST':
        snippet = get_object_or_404(Snippet, pk = snippet_id)
        Bookmark.objects.filter(user__pk = request.user.id,
                snippet__pk = snippet.id).delete()
        return HttpResponseRedirect(snippet.get_absolute_url())
    else:
        return render_to_response('cab/confirm_bookmark_delete.html',
                {'snippet': snippet})
delete_bookmark = login_required(delete_bookmark)

def user_bookmarks(request):
    return object_list(queryset = Bookmark.objects.filter(user__pk = request.user.id),
            template_name = 'cab/user_bookmarks.html',
            paginate_by = 20)

learning/djangoLearning/PracticalDjangoProjects2ndEdition/Version1.2/simplecms/src/simplecms/cab/views/languages.py
#coding=utf8
from django.shortcuts import get_object_or_404
from django.views.generic.list_detail import object_list
from simplecms.cab.models import Language

def language_detail(request, slug):
    language = get_object_or_404(Language, slug = slug)
    return object_list(request,
            queryset = language.snippet_set.all(),
            paginate_by = 20,
            template_name = 'cab/language_detail.html',
            extra_context = {'language': language})

learning/djangoLearning/PracticalDjangoProjects2ndEdition/Version1.2/simplecms/src/simplecms/cab/views/popular.py
#coding=utf8
from django.views.generic.list_detail import object_list
from simplecms.cab.models import Language, Snippet
from django.contrib.auth.models import User
from django.db.models import Count

def top_authors(request):
    return object_list(request, queryset = Snippet.objects.top_authors(),
                       template_name = 'cab/top_authors.html',
                       paginate_by = 20)

def top_languages(request):
    return object_list(request,
                       queryset = Language.objects.top_languages(),
                       template_name = 'cab/top_languages.html',
                       paginate_by = 20)
    
def most_bookmarked(request):
    return object_list(queryset = Snippet.objects.most_bookmarked(),
                       template_name = 'cab/most_bookmarked.html',
                       paginate_by = 20)
"""
User.objects.annotate(score = Count('snippet')).order_by('score')

def top_authors(request):
    top_authors_qs = User.objects.annotate(score = Count('snippet')).order_by('score')
    return object_list(request, queryset = top_authors_qs,
                       template_name = 'cab/top_authors.html',
                       paginate_by = 20)
"""

learning/djangoLearning/PracticalDjangoProjects2ndEdition/Version1.2/simplecms/src/simplecms/cab/views/snippets.py
#coding=utf8
from django.http import HttpResponseForbidden, HttpResponseRedirect
from django.forms import ModelForm, Textarea
from django.shortcuts import get_object_or_404, render_to_response
from django.contrib.auth.decorators import login_required
from simplecms.cab.models import Snippet

class SnippetForm(ModelForm):
    class Meta:
        model = Snippet
        exclude = ['author']
        widgets = {'code': Textarea(attrs={'cols': 80, 'rows': 10})}

        
def add_snippet(request):
    if request.method == 'POST':
        form = SnippetForm(data = request.POST)
        if form.is_valid():
            new_snippet = form.save(commit = False)
            new_snippet.author = request.user
            new_snippet.save()
            return HttpResponseRedirect(new_snippet.get_absolute_url())
    else:
        form = SnippetForm()
    return render_to_response('cab/snippet_form.html',
                              {'form': form, 'add': True})
add_snippet = login_required(add_snippet)


def edit_snippet(request, snippet_id):
    snippet = get_object_or_404(Snippet, pk = snippet_id)
    if request.user.id != snippet.author.id:
        return HttpResponseForbidden()
    if request.method == 'POST':
        form = SnippetForm(instance = snippet, data = request.POST)
        if form.is_valid():
            snippet = form.save()
            return HttpResponseRedirect(snippet.get_absolute_url())
    else:
        form = SnippetForm(instance = snippet)
    return render_to_response('cab/snippet_form.html',
                                  {'form': form, 'add': False})
edit_snippet = login_required(edit_snippet)

learning/djangoLearning/PracticalDjangoProjects2ndEdition/Version1.2/simplecms/src/simplecms/templates/cab/add_snippet.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
 "http://www.w3.org/TR/html4/loose.dtd">
<html>
 <head>
  <title>Add a snippet</title>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
 </head>
 <body>
   <h1>Add a snippet</h1>
   <p>
     Use the form below to submit your snippet; all fields are required.
   </p>
   <form method="post" action="">
     {% csrf_token %}
     {# title #}
     <p>
       {% if form.title.errors %}
         <span class="error">{{ form.title.errors|join:", " }}</span>
       {% endif %}
     </p>
     <p>
       <label for="id_title">Title:</label>
       {{ form.title }}
     </p>

     {# language #}
     <p>
       {% if form.language.errors %}
         <span class="error">{{ form.language.errors|join:", " }}</span>
       {% endif %}
     </p>
     <p>
       <label for="id_languages">Language:</label>
       {{ form.language }}
     </p>

     {# description #}
     <p>
       {% if form.description.errors %}
         <span class="error">{{ form.description.errors|join:", " }}</span>
       {% endif %}
     </p>
     <p>
       <label for="id_description">Description:</label>
       {{ form.description }}
     </p>

     {# code #}
     <p>
       {% if form.code.errors %}
         <span class="error">{{ form.code.errors|join:", " }}</span>
       {% endif %}
     </p>
     <p>
       <label for="id_code">Code:</label>
       {{ form.code }}
     </p>

     {# tags #}
     <p>
       {% if form.tags.errors %}
         <span class="error">{{ form.tags.errors|join:", " }}</span>
       {% endif %}
     </p>
     <p>
       <label for="id_tags">Tags:</label>
       {{ form.tags }}
     </p>
     <p>
       <input type="submit" value="Submit">
     </p>
   </form>
 </body>
</html>

learning/djangoLearning/PracticalDjangoProjects2ndEdition/Version1.2/simplecms/src/simplecms/templates/cab/base_cab.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
 "http://www.w3.org/TR/html4/loose.dtd">
<html>
 <head>
  <title>
    {% block title %}
      Snippets
    {% endblock %}
  </title>

  {% block css %}
  {% endblock %}

  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
 </head>
 <body class="{% block bodyclass %}{% endblock %}">

   <div id="header">
     <h1 id="branding">Snippets</h1>
   </div>

   <div id="content">
     {% block content %}
     {% endblock %}
   </div>

   {% comment %}
   <div id="sidebar">
     <h2>Navigation</h2>
     <ul id="main-nav">
       <li id="main-nav-entries">
         <a href="{% url coltrane_entry_archive_index %}">Entries</a>
       </li>
       <li id="main-nav-snippets">
       </li>
     </ul>
   </div>
   {% endcomment %}

 </body>
</html>

learning/djangoLearning/PracticalDjangoProjects2ndEdition/Version1.2/simplecms/src/simplecms/templates/cab/base_tags.html
{% extends "cab/base_cab.html" %}

{% block title %}
  {{ block.super }}
  | Tags
{% endblock %}

{% block bodyclass %}tags{% endblock %}

learning/djangoLearning/PracticalDjangoProjects2ndEdition/Version1.2/simplecms/src/simplecms/templates/cab/language_detail.html
{% extends "cab/base_cab.html" %}

{% block title %}
  {{ block.super }}
  | Languages
{% endblock %}

{% block bodyclass %}language{% endblock %}

{% block content %}
  <h1>Snippets in language "{{ language }}"</h1>
  {% if object_list %}
    {# 检索到结果 #}
    {% for snippet in object_list %}
      <h2>{{ snippet.title }}</h2>
      <p>
        <b>Author:</b>
        {{ snippet.author }}<br/>

        <b>Published on</b>
        {{ snippet.pub_date|date:"Y年Fj日" }}<br/>

        <b>Updated on</b>
        {{ snippet.updated_date|date:"Y年Fj日" }}<br/>

        <b>Description:</b>
        {{ snippet.description_html|safe }}

        <a href="{{ snippet.get_absolute_url }}">Read full snippet</a>
      </p>
    {% endfor %}
  {% else %}
    {# 未检索到结果 #}
    <p>
      There is no any snippet in language "{{ language }}"
    </p>
  {% endif %}
{% endblock %}

learning/djangoLearning/PracticalDjangoProjects2ndEdition/Version1.2/simplecms/src/simplecms/templates/cab/language_list.html
{% extends "cab/base_cab.html" %}

{% block title %}
  {{ block.super }}
  | Languages
{% endblock %}

{% block bodyclass %}languages{% endblock %}

{% block content %}
  <h1>Languages</h1>
  {% if object_list %}
    {% for language in object_list %}
      <h2>{{ language.name }}</h2>
      <p>
        <b>Language code:</b>
        {{ language.language_code }}<br>

        <b>Mime type:</b>
        {{ language.mime_type }}<br>
      </p>
      <a href="{{language.get_absolute_url}}">Read language details</a>
    {% endfor %}
  {% endif %}
{% endblock %}

learning/djangoLearning/PracticalDjangoProjects2ndEdition/Version1.2/simplecms/src/simplecms/templates/cab/snippet_detail.html
{% extends "cab/base_cab.html" %}

{% block title %}
  {{ block.super }}
  | {{ object.title }}
{% endblock %}

{% block css %}
  <link rel="stylesheet" type="text/css" href="/css/cab/pygments/pygments_colorful.css">
{% endblock %}

{% block content %}
  <h2>{{ object.title }}</h2>
  <p>
    <b>Language:</b>
    {{ object.language }}<br/>

    <b>Author:</b>
    {{ object.author }}<br/>

    <b>Published on:</b>
    {{ object.pub_date|date:"Y年Fj日" }}<br/>

    <b>Updated on:</b>
    {{ object.updated_date|date:"Y年Fj日" }}<br/>

    <b>Description:</b>
    {{ object.description_html|safe }}<br/>

    <b>Code:</b>
    {{ object.highlighted_code|safe }}<br/>
  </p>

  {# 下面关于标签 #}
  {% if object.tags %}
    <p>
      This snippet is tagged with
      {% for tag in object.tags.split %}
        <a href="/snippets/tags/{{ tag }}/">{{ tag.title|lower }}</a>
        {% if forloop.last %}
        {% else %}
          {% ifequal forloop.revcounter0 1 %}and {% else %}, {% endifequal %}
        {% endif %}
      {% endfor %}.
    </p>
  {% endif %}

  <p>This snippet is written in <a href="{{ object.language.get_absolute_url }}">{{ object.language }}</a>.</p>
{% endblock %}

learning/djangoLearning/PracticalDjangoProjects2ndEdition/Version1.2/simplecms/src/simplecms/templates/cab/snippet_form.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
 "http://www.w3.org/TR/html4/loose.dtd">
<html>
 <head>
  <title>
    {% if add %}
      Add a
    {% else %}
      Edit your
    {% endif %}
    snippet
  </title>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
 </head>
 <body>
   <h1>
     {% if add %}
       Add a
     {% else %}
       Edit your
     {% endif %}
     snippet
   </h1>
   <p>
     Use the form below to 
     {% if add %}
       Add a
     {% else %}
       Edit your
     {% endif %}
     snippet; all fields are required.
   </p>
   <form method="post" action="">
     {% comment %}
     {{ form.as_table }}
     {{ form.as_ul }}
     {% endcomment %}
     {{ form.as_p }}
     <p>
       <input type="submit" value="Submit">
     </p>
   </form>
 </body>
</html>

learning/djangoLearning/PracticalDjangoProjects2ndEdition/Version1.2/simplecms/src/simplecms/templates/cab/snippet_list.html
{% extends "cab/base_cab.html" %}

{% block title %}
  Snippets
{% endblock %}

{% block content %}

  {% if object_list %}
    {% for snippet in object_list %}
      <h2>{{ snippet.title }}</h2>
      <p>
        <b>Author:</b>
        {{ snippet.author }}<br/>

        <b>Published on</b>
        {{ snippet.pub_date|date:"Y年Fj日" }}<br>

        <b>Updated on</b>
        {{ snippet.updated_date|date:"Y年Fj日" }}<br/>

        <b>Description:</b>
        {{ snippet.description_html|safe }}<br/>

        <a href="{{ snippet.get_absolute_url }}">Read full snippet</a>
      </p>
    {% endfor %}
  {% endif %}

  <p>
    {% if has_previous %}
      <a href="?page={{ previous }}">第{{ previous }}页</a>
    {% endif %}
    第{{ page }}页
    {% if has_next %}
      <a href="?page={{ next }}">第{{ next }}页</a>
    {% endif %}
  </p>

{% endblock %}

learning/djangoLearning/PracticalDjangoProjects2ndEdition/Version1.2/simplecms/src/simplecms/templates/cab/snippets_by_tag.html
{% extends "cab/base_tags.html" %}

{% block title %}
  {{ block.super }}
  | Snippets by tag {{ tag }}
{% endblock %}

{% block content %}
  <h1>Snippets by tag {{ tag }}</h1>
  {% for snippet in object_list %}
    <h2>{{ snippet.title }}</h2>
    <p>
      <b>Author:</b>
      {{ snippet.author }}<br/>

      <b>Published on</b>
      {{ snippet.pub_date|date:"Y年Fj日" }}<br/>

      <b>Updated on</b>
      {{ snippet.updated_date|date:"Y年Fj日" }}<br/>

      <b>Description:</b>
      {{ snippet.description_html|safe }}

      <a href="{{ snippet.get_absolute_url }}">Read full snippet</a>
    </p>
  {% endfor %}
{% endblock %}