learning/djangoLearning/ddtcms/src/ddtcms/captcha/urls.py
from django.conf.urls.defaults import *
urlpatterns = patterns('',
    (r'(?P<token_uid>\w+).jpg$','captcha.views.captcha_image'),
)


learning/djangoLearning/ddtcms/src/ddtcms/member/urls.py
from django.conf.urls.defaults import *
from ddtcms.home.views import common_dict
from ddtcms.member.models import Profile,Resume

common_dict.update({'app_label':'member',    })
    
    
member_dict = {
'queryset': Profile.objects.all(),
'extra_context':common_dict,
'template_name':'member/index.html',
}


pages_dict = {
'queryset': Profile.objects.all(),
'extra_context':common_dict,
'paginate_by':1,
}


urlpatterns = patterns('',
    (r'^$',                            'django.views.generic.list_detail.object_list', member_dict),


)

learning/djangoLearning/ddtcms/src/ddtcms/tagging/urls.py
from django.conf.urls.defaults import *
from tagging.views import tagged_object_list

urlpatterns = patterns('',
    #(r'^$',                    'django.views.generic.date_based.archive_index', todo_dict),
    url(r'^$',                  'tagging.views.index', name='tagging-index'),
    url(r'^(?P<tag>[-\w]+)/$',  'tagging.views.by_tag',name='tagged_object_list'),
)

urlpatterns += patterns('',
    url(r'^tr/(\d+)/(\w+)/$', 'django.views.defaults.shortcut', name='tag-url-redirect'),
)

learning/djangoLearning/ddtcms/src/ddtcms/urls.py
from django.conf.urls.defaults import *
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

from django.views.generic.simple import direct_to_template
from django.contrib.sitemaps import FlatPageSitemap, GenericSitemap
from ddtcms.blog.sitemaps import BlogSitemap
from ddtcms.blog.models import Blog

from ddtcms.member.views import get_profiles


from django.contrib.contenttypes.models import ContentType
from django.http import HttpResponseRedirect

def export_selected_objects(modeladmin, request, queryset):
    selected = request.POST.getlist(admin.ACTION_CHECKBOX_NAME)
    ct = ContentType.objects.get_for_model(queryset.model)
    return HttpResponseRedirect("/export/?ct=%s&ids=%s" % (ct.pk, ",".join(selected)))

admin.site.add_action(export_selected_objects)

info_dict = {
    'queryset': Blog.objects.all(),
    'date_field': 'pub_date',
}

sitemaps = {
    'flatpages': FlatPageSitemap,
    'blog': BlogSitemap,
}






from ddtcms import settings

urlpatterns = patterns('',
    # Example:
    # (r'^ddtcms/', include('ddtcms.foo.urls')),
    (r'^', include('ddtcms.home.urls')),
    (r'^(?i)news/', include('ddtcms.news.urls')),
    (r'^(?i)saying/', include('ddtcms.saying.urls')),
    (r'^(?i)forum/', include('ddtcms.forum.urls')),
    (r'^(?i)faq/', include('ddtcms.faq.urls')),
    (r'^(?i)polls/', include('ddtcms.polls.urls')),
    (r'^(?i)blog/', include('ddtcms.blog.urls')),
    (r'^(?i)book/', include('ddtcms.book.urls')),
    (r'^(?i)captcha/', include('ddtcms.captcha.urls')),
    (r'^(?i)notice/', include('ddtcms.notice.urls')),
    (r'^(?i)link/', include('ddtcms.link.urls')),
    (r'^(?i)people/', include('ddtcms.people.urls')),
    (r'^(?i)todo/', include('ddtcms.todo.urls')),
    (r'^(?i)guestbook/', include('ddtcms.guestbook.urls')),
    
    (r'^(?i)member/', include('ddtcms.member.urls')),
    (r'^(?i)member/$', direct_to_template, {'extra_context': { 'profiles': get_profiles }, 'template': 'member/front.html' }),
    
    (r'^(?i)photologue/', include('photologue.urls')),
    (r'^(?i)photologue/$', direct_to_template, {'template': 'photologue/index.html' }),

    (r'^(?i)attachments/', include('attachments.urls')),
    (r'^(?i)tags/', include('tagging.urls')),
    
    
    # serve static medias
    (r'^(?i)media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    (r'^(?i)themes/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_THEMES}),
    (r'^(?i)images/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_IMAGE}),
    (r'^(?i)css/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_CSS}), 	
    (r'^(?i)js/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_JS}), 		
    (r'^(?i)upload/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_UPLOAD}),
    (r'^(?i)editor/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_EDITOR}),
    (r'^(?i)attachment/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_UPLOAD + "attachment/"}),
    
    	    
    (r'^(?i)sitemap.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
    (r'^(?i)sitemap-(?P<section>.+).xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
    
    # user django comments system    
    (r'^(?i)comments/', include('django.contrib.comments.urls')),
    
    # Uncomment the admin/doc line below and add 'django.contrib.admindocs'
    # to INSTALLED_APPS to enable admin documentation:
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    
    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),


)


# Serves media content. WARNING!! Only for development uses.
# On production use lighthttpd for media content.
if settings.DEBUG:

    # Delete the first trailing slash, if any.
    if settings.MEDIA_URL.startswith('/'):
        media_url = settings.MEDIA_URL[1:]
    else:
        media_url = settings.MEDIA_URL

    # Add the last trailing slash, if have not.
    if not media_url.endswith('/'):
        media_url = media_url + '/'

    urlpatterns += patterns('',
        (r'^' + media_url + '(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}
        ),
    )

learning/djangoLearning/ddtcms/src/ddtcms/member/forms.py
from django import forms
from django.core.exceptions import ObjectDoesNotExist
from django.core.exceptions import ImproperlyConfigured
from django.db import models
from django.utils.translation import ugettext as _
from django.conf import settings
from django.contrib.auth.models import User
from ddtcms.member.models import EmailValidation
from django.core.files.uploadedfile import SimpleUploadedFile
import mimetypes, urllib

from ddtcms.captcha.forms import *

if not settings.AUTH_PROFILE_MODULE:
    raise SiteProfileNotAvailable
try:
    app_label, model_name = settings.AUTH_PROFILE_MODULE.split('.')
    Profile = models.get_model(app_label, model_name)
except (ImportError, ImproperlyConfigured):
    raise SiteProfileNotAvailable

class LocationForm(forms.ModelForm):
    """
    Profile location form
    """

    class Meta:
        model = Profile
        fields = ('location', 'latitude', 'longitude', 'country')

class ProfileForm(forms.ModelForm):
    """
    Profile Form. Composed by all the Profile model fields.
    """
    class Meta:
        model = Profile
        exclude = ('date', 'location', 'latitude', 'longitude', 'country',
                   'user', 'public')

class PublicFieldsForm(forms.ModelForm):
    """
    Public Fields of the Profile Form. Composed by all the Profile model fields.
    """
    class Meta:
        model = Profile
        exclude = ('date', 'user', 'public')

class AvatarForm(forms.Form):
    """
    The avatar form requires only one image field.
    """
    photo = forms.ImageField(required=False)
    url = forms.URLField(required=False)

    def clean_url(self):
        url = self.cleaned_data.get('url')
        if not url: return ''
        filename, headers = urllib.urlretrieve(url)
        if not mimetypes.guess_all_extensions(headers.get('Content-Type')):
            raise forms.ValidationError(_('The file type is invalid: %s' % type))
        return SimpleUploadedFile(filename, open(filename).read(), content_type=headers.get('Content-Type'))

    def clean(self):
        if not (self.cleaned_data.get('photo') or self.cleaned_data.get('url')):
            raise forms.ValidationError(_('You must enter one of the options'))
        return self.cleaned_data

class AvatarCropForm(forms.Form):
    """
    Crop dimensions form
    """
    top = forms.IntegerField()
    bottom = forms.IntegerField()
    left = forms.IntegerField()
    right = forms.IntegerField()

    def clean(self):
        if int(self.cleaned_data.get('right')) - int(self.cleaned_data.get('left')) < 96:
            raise forms.ValidationError(_("You must select a portion of the image with a minimum of 96x96 pixels."))
        else:
            return self.cleaned_data

class RegistrationForm(forms.Form):
	# 2009-7-9 20:29:28 to capatite with dedecms's css 
	# use css attrs={'class': 'ipt-txt'}
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'ipt-txt'}),max_length=255, min_length = 3, label=_("Username"))
    email = forms.EmailField(widget=forms.TextInput(attrs={'class':'ipt-txt'}),
    						required=hasattr(settings, "REQUIRE_EMAIL_CONFIRMATION") and settings.REQUIRE_EMAIL_CONFIRMATION or False, 
    						label=_("E-mail address"))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'ipt-txt'}), label=_("Password"))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'ipt-txt'}), label=_("Password (again)"))
    captcha_uid = forms.CharField(
            required=True,
            label="",
            max_length=40,
            widget=CaptchaUID)
    
    captcha = forms.CharField(
            required=True,
            label="Verify Code",
            max_length=1000,
            widget=CaptchaInput)
 
    def clean_captcha(self):
        return validate_captcha(self)
        
    def clean_username(self):
        """
        Verify that the username isn't already registered
        """
        username = self.cleaned_data.get("username")
        #if not set(username).issubset("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_"):
        #    raise forms.ValidationError(_("That username has invalid characters. The valid values are letters, numbers and underscore."))
        
        if set("'").issubset(username) or set("\"").issubset(username) or set("|").issubset(username) or set(";").issubset(username) or set(",").issubset(username) or set("=").issubset(username) or set("!").issubset(username):
        	raise forms.ValidationError(_("That username has invalid characters. The valid values are letters, numbers and underscore."))

        if User.objects.filter(username__iexact=username).count() == 0:
            return username
        else:
            raise forms.ValidationError(_("The username is already registered."))

    def clean(self):
        """
        Verify that the 2 passwords fields are equal
        """
        if self.cleaned_data.get("password1") == self.cleaned_data.get("password2"):
            return self.cleaned_data
        else:
            raise forms.ValidationError(_("The passwords inserted are different."))

    def clean_email(self):
        """
        Verify that the email exists
        """
        email = self.cleaned_data.get("email")

        if not email: return  email

        try:
            User.objects.get(email=email)
            raise forms.ValidationError(_("That e-mail is already used."))
        except User.DoesNotExist:
            try:
                EmailValidation.objects.get(email=email)
                raise forms.ValidationError(_("That e-mail is already being confirmed."))
            except EmailValidation.DoesNotExist:
                return email

class EmailValidationForm(forms.Form):
    email = forms.EmailField()

    def clean_email(self):
        """
        Verify that the email exists
        """
        email = self.cleaned_data.get("email")
        if not (User.objects.filter(email=email) or EmailValidation.objects.filter(email=email)):
            return email

        raise forms.ValidationError(_("That e-mail is already used."))

class ResendEmailValidationForm(forms.Form):
    email = forms.EmailField()

    def clean_email(self):
        """
        Verify that the email exists
        """
        email = self.cleaned_data.get("email")
        if User.objects.filter(email=email) or EmailValidation.objects.filter(email=email):
            return email

        raise forms.ValidationError(_("That e-mail isn't registered."))

learning/djangoLearning/ddtcms/src/ddtcms/member/templates/member/avatar/choose.html
{% extends "member/base_2col.html" %}
{% load i18n %}

{% block title %}选择您的头像的位置{% endblock %}
{% block robots %}noindex,nofollow{% endblock %}

{% block js.custom %}
<script type="text/javascript">
	$(function() {
	//avatar
		$("a.delavatar").click(function() {
			$.getJSON($(this).attr("href"), function(data) {
				if (data.success) {
					$("img#avatarimg").attr("src", "{{ generic96 }}");
					$("p#avatardelete").remove();
				}
			});
			return false;
		});
	});
</script>
{% endblock %}

{% block userprofile_navigation %}
{% include "member/menu.html" %}
{% endblock %}

{% block userprofile_content %}
	<form class="yform" action="" method="post" accept-charset="utf-8" enctype="multipart/form-data">
		{% if form.errors %}
			{% for error,desc in form.errors.items %}
				<p class="error">{{desc|join:"; "}}</p>
			{% endfor %}
		{% endif %}
		<fieldset>
			<legend>选择您的头像的位置</legend>
			<ul>
			<li>
				<label for="id_photo">从磁盘选择一个图像:</label>
				<p>{{ form.photo }}
				<input type="submit" value="完成" />
				</p>
			</li>
			<li>
				<label for="id_url">从远程的URL选择一个图像,请您将图像的URL填入下面的输入框内,我们将根据URL地址把图片下载到服务器上来:</label>
				<p>{{ form.url }}
				<input type="submit" value="完成" />
				</p>
			</li>
			{% if AVATAR_WEBSEARCH %}
			<li>
				<a class="large" href="{{ request.path_info }}search/">在 Picasa Web 搜索一个图像</a>
			</li>
			{% endif %}
			</ul>
		</fieldset>
		</form>
{% endblock %}

{% block userprofile_content_related %}
  <div class="box">
    <h3>头像选择页面</h3>
		<p>您有几种选择去选取图像作为您的档案中的个性头像.</p>
  </div>

	{% load avatars %}
  <div class="center">
		<img class="border" id="avatarimg" src="{% avatar 96 %}" />
    {% if user.get_profile.has_avatar %}<p id="avatardelete" style="text-align: center;"><a href="{{ request.path_info }}delete/" class="delavatar">删除</a></p>{% endif %}
	</div>
{% endblock %}

learning/djangoLearning/ddtcms/src/ddtcms/member/templates/member/avatar/crop.html
{% extends "member/base_2col.html" %}
{% load i18n %}

{% block title %}按你想要的剪切图像和改变大小{% endblock %}
{% block robots %}noindex,nofollow{% endblock %}

{% block js.custom %}
<script type="text/javascript" src="{{ MEDIA_URL }}js/jquery.imgareaselect-0.4.2.min.js"></script>
<script type="text/javascript">
	$(function() {
		function updateValues(img, selection) {
			$("input[name='left']").val(selection.x1);
			$("input[name='top']").val(selection.y1);
			$("input[name='right']").val(selection.x2);
			$("input[name='bottom']").val(selection.y2);
		}
		$(window).load(function() {
			$("#cropimage").imgAreaSelect({ aspectRatio: "1:1", onSelectEnd: updateValues });
		});
	});
</script>
{% endblock %}

{% block userprofile_navigation %}
{% include "member/menu.html" %}
{% endblock %}

{% block userprofile_content %}
	<form action="{{ request.path_info }}" method="post" accept-charset="utf-8">
	<fieldset>
		<legend>裁剪和改变选区的到你想要的大小</legend>

		{% if form.errors %}
			{% for error,desc in form.errors.items %}
				<p class="error">{{desc|join:"; "}}</p>
			{% endfor %}
		{% endif %}

		<div style="text-align: center;">
			<img src="{{ avatar.image.url }}" id="cropimage" />
		</div>
		<input type="hidden" name="top" value="0"/>
		<input type="hidden" name="bottom" value="0"/>
		<input type="hidden" name="left" value="0"/>
		<input type="hidden" name="right" value="0"/>
	</fieldset>
	<input type="submit" class="done" value="完成" />
	</form>
{% endblock %}

{% block userprofile_content_related %}
  <div class="box">
    <h3>头像选择页面</h3>
    <p>您有几种选择去选取图像作为您的档案中的个性头像.</p>
  </div>

  {% load avatars %}
  <div class="center">
    <img class="border" id="avatarimg" src="{% avatar 96 %}" />
  </div>

{% endblock %}

learning/djangoLearning/ddtcms/src/ddtcms/member/templates/member/avatar/done.html
{% extends "member/base_2col.html" %}
{% load i18n %}

{% block title %}头像选择成功{% endblock %}
{% block robots %}noindex,nofollow{% endblock %}

{% block userprofile_navigation %}
{% include "member/menu.html" %}
{% endblock %}

{% block userprofile_content %}
	<p class="success large">
		您的新头像已经被成功保存.
	</p>
{% endblock %}

{% block userprofile_content_related %}
  <div class="box">
    <h3>头像选择页面</h3>
    <p>您有几种选择去选取图像作为您的档案中的个性头像.</p>
  </div>

  {% load avatars %}
  <div class="center">
    <img class="border" id="avatarimg" src="{% avatar 96 %}" />
  </div>

{% endblock %}

learning/djangoLearning/ddtcms/src/ddtcms/member/templates/member/avatar/search.html
{% extends "member/base_2col.html" %}
{% load i18n %}

{% block title %}{% trans "Search for an image on Picasa Web" %}{% endblock %}
{% block robots %}noindex,nofollow{% endblock %}

{% block js.custom %}
<script type="text/javascript">
	$(function() {
		$("input[type='text']").focus();
		$("input[type='text']").addClass("text");
		$("div.photos a").click(function() {
			$("form#avatar input[name='url']").val($(this).attr("href"));
			$("form#avatar").submit();
			return false;
		});
	});
</script>
{% endblock %}

{% block userprofile_navigation %}
{% include "member/menu.html" %}
{% endblock %}

{% block userprofile_content %}
	<form action="" method="post" accept-charset="utf-8">
	<fieldset>
		<legend>{% trans "Search for an image on Picasa Web" %}</legend>
		<label for="id_search">{% trans "Search on Picasa Web" %}</label>
		<p>
			<input type="text" name="keyword" value="{{ keyword }}" />
			<input type="submit" value="{% trans "Search" %}"/>
		</p>

		<div class="photos">
			{% for thumb,url in images.items %}
			<a href="{{ url }}"><img src="{{ thumb }}" /></a>
			{% endfor %}
		</div>
	</fieldset>
	</form>

	<form class="hide" id="avatar" action="{% url profile_edit_avatar %}" method="post" accept-charset="utf-8">
		<input type="hidden" name="url" value="" />
	</form>
{% endblock %}

{% block userprofile_content_related %}
  <div class="box">
    <h3>{% trans "Avatar selection page" %}</h3>
    <p>{% trans "You have several options to select the image you want as avatar on your profile" %}.</p>
  </div>

  {% load avatars %}
  <div class="center">
    <img class="border" id="avatarimg" src="{% avatar 96 %}" />
  </div>

{% endblock %}