learning/djangoLearning/makestory-whhhy/feedback/urls.py
from django.conf.urls.defaults import *
from views import FeedbackViews

urlpatterns = patterns('',
    (r'^$',FeedbackViews.feedback),
    (r'^ajax/$','feedback.views.ajax'),
    (r'^delete/$','feedback.views.delete'),
)

learning/djangoLearning/makestory-whhhy/feedback/models.py
#coding=utf-8
from django.db import models
from daily.models import Daily

class Customer(models.Model):
    name = models.CharField('名字',max_length=14,)
    email = models.EmailField()
    date = models.DateField('注册日期',auto_now_add=True)
    class Meta:
        verbose_name = '留言者'
        verbose_name_plural = '留言者'
    def __unicode__(self):
        return self.name
    
  

class Message(models.Model):
    customer = models.ForeignKey(Customer,verbose_name ='留言人')
    content = models.TextField('内容')
    date = models.DateTimeField('日期',auto_now_add=True)
    ip = models.CharField('IP地址',max_length=20)
    reply=models.TextField('回复',blank=True)
    show = models.BooleanField('显示',default=True)
    at = models.ForeignKey(Daily,blank=True,null=True,verbose_name ='关联')
    
    def save(self):
        models.Model.save(self)
        if self.at:
            self.at.count=Message.objects.filter(at=self.at).count()
            self.at.save()
    def delete(self):
        models.Model.delete(self)
        if self.at:
            self.at.count=Message.objects.filter(at=self.at).count()
            self.at.save()
    class Meta:
        ordering=['-date']
        verbose_name = '留言'
        verbose_name_plural = '留言'
    def __unicode__(self):
        return "%s:%s..." % (self.customer.name,self.content[0:30])

learning/djangoLearning/makestory-whhhy/feedback/forms.py
#coding=utf-8
from django import forms
from models import Message,Customer

noname = u'\u4e00\u4e2a\u4e0d\u613f\u900f\u9732\u59d3\u540d\u7684\u5bb6\u4f19' #一个不愿透露姓名的家伙

class MessageForm(forms.Form):
    content = forms.CharField(required=False)
    name = forms.CharField(max_length=10,required=False)
    email = forms.EmailField(required=False)
    def clean_content(self):
        content = self.cleaned_data['content'].strip()
        if not content:
            raise forms.ValidationError("留言内容不能为空")
        return content
    
    def clean_name(self):
        name = self.cleaned_data.get('name').strip()
        if name=='':
                name = noname
        return name
    
    def clean_email(self):
        email = self.cleaned_data.get('email')
        name = self.cleaned_data.get('name',u'').strip()
        if name == noname:
            email='unknow@whhhy.com'
        if email=='':
            raise forms.ValidationError("如果您要留名的话请输入邮箱地址")
     
        try:
            exist=Customer.objects.filter(name=name)[0]
        except:
            c=Customer(name=name,email=email)
            c.save()
            return email
        if exist.email != email:
            raise forms.ValidationError("邮箱与此用户名不匹配")
            return email
        return email
        
            
  

learning/djangoLearning/makestory-whhhy/feedback/views.py
#coding=utf-8
from django.http import Http404,HttpResponse
from django.shortcuts import render_to_response
from feedback.models import Message,Customer
from feedback.forms import MessageForm
from daily.models import Daily
from base import BaseView

def ajax(request):
    if request.method == 'POST':
        url  = request.META['HTTP_REFERER']
        date = url[-11:-1]
        form = MessageForm(request.POST)
        try:
            daily = Daily.objects.get(date=date)
        except:
            daily = None
        if form.is_valid():
            content = form.cleaned_data['content']
            name    = form.cleaned_data['name']
            email   = form.cleaned_data['email']
            ip      = request.META['REMOTE_ADDR']
            at      = daily
            m       = Message(customer=Customer.objects.get(name = name),content = content,ip = ip,at = at)
            m.save()
            number=Message.objects.filter(at=daily).count()
            return render_to_response('ajax.xml', {'form':form,'message':m,'number':number,'ok':True})
        else:
            return render_to_response('ajax.xml', {'form':form,'ok':False})
    else:
        return render_to_response('ajax.xml', {'ok':False})

def delete(request):
    pk = int(request.POST['pk'])
    Message.objects.get(pk=pk).delete()
    script ="<script> $('#pk%s').slideUp()</script>" % pk
    return HttpResponse(script)
    


class FeedbackViews(BaseView):
    @classmethod
    def feedback(self,request):
        template='feedback.html'
        para=BaseView().para
        para['repeat']=False
        para['messages'] = Message.objects.filter(show=True)[:30]
        if request.method == 'POST':
            form = MessageForm(request.POST)
            para['form']= form
            if form.is_valid():
                content = form.cleaned_data['content']
                name    = form.cleaned_data['name']
                email   = form.cleaned_data['email']
                ip      = request.META['REMOTE_ADDR']
                at      = None
                m       = Message(customer=Customer.objects.get(name=name),content=content,ip=ip,at=at)
                try:
                    if content==para['messages'][0].content:
                        para['repeat']=True
                        return render_to_response(template, para)
                    else:
                        m.save()
                        para['ok']=True
                        return render_to_response(template, para)
                except:
                    para['ok']=True
                    m.save()
                    return render_to_response(template, para)
            else:
                wrong = request.POST
                wrong.name = form['name']
                wrong.email = form['email']
                wrong.content = form['content']
                para['worng'] = wrong
                return render_to_response(template, para)
        else:
            para['form'] = MessageForm()
            return render_to_response(template, para)

learning/djangoLearning/makestory-whhhy/feedback/templates/errors.html
{% if form.errors or repeat%}
<div id="error">
    {% if repeat %}<p>不要连续发重复内容</p>{%endif%}
        <p>{{form.content.errors}}</p>
        <p>{{form.email.errors}}</p>
        <p>{{form.name.errors}}</p>
</div>
{% endif%}

learning/djangoLearning/makestory-whhhy/feedback/templates/feedback.html
{% extends "base.html" %}
{% block ajax %}
<script type="text/javascript">
function ajaxsend(){
    $('#error').remove(); 
    $.ajax({
        url:'/feedback/ajax/',
        type: 'POST',
        dataType:'xmlDoc',
        data:{name:$("#id_name").val(),content:$("#id_content").val(),email:$("#id_email").val(),},
        beforeSend:function(){$('.messages h3').after('<div id="sending"><p>正在发送……</p></div>');},
        success: function(xmlDoc){
        $('.messages h3').after(xmlDoc);
        $('.message:first').animate({ height: 'show' });
        $('#sending').remove()
        },
        });
        return false;};
$(document).ready(function(){
    $("#feedback").submit(ajaxsend);
     });
</script>
{% endblock %}
{%block page%}
<div id="page">
    {% include "form.html" %}
    {% include "errors.html" %}
     <div class="cap"></div>
<div class="messages">
     <h3>大家的留言</h3>
{% for message in messages %}
<div class="message">
    <div class="info">
        <div class="header">
        <p class="name">{{message.customer.name}} 说: </p>
        <span class="time">{{message.date|date:"Y.n.j H:i"}}</span>
        </div>
        <div class="counter">
             {%if message.at.date%}<span class="at"> 在<a href='{{message.at.url}}'>{{message.at.date|date:"y年n月j日"}}的日志</a>中</span>{%endif%} 
        </div>
    </div>
    
    <div class="say">
    <p>{{message.content|linebreaksbr}}</p>
    
    </div>
</div>
{% endfor %}
</div>

    <div class="footer"></div>
</div>
{%endblock%}

learning/djangoLearning/makestory-whhhy/feedback/templates/form.html
<form method="post" action="#feedback" id="feedback">
    <div id="topfield" class="field">
        <p><label for="id_content">+留言</label></p>
        <textarea  id="id_content" name="content"  rows="6" cols="60">{{wrong.content}}</textarea>
    </div>
    <div id="midfield" class="field"> 
    </div>
    <div id="bottomfield" class="field">
        <div id="showsign">
            <span>我要留名</span>
        </div>
        <div id="sign">
            <label for="id_name">称呼</label>
            <input type="text"  maxlength="10" name="name" id="id_name" value="{{wrong.name}}" />
            <label for="id_email">邮箱</label>
            <input type="text" id="id_email" name="email" value="{{wrong.email}}" />
        </div>
        <div id="submit">
            <input id="sub" type="submit" value="写好啦!"/>
        </div>
    </div>
</form> 