learning/djangoLearning/mysite/urls.py
from django.conf.urls.defaults import *
from django.conf import settings
#from mysite.views import hello,current_datetime, hours_ahead,index,checkbrowser,display_meta

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('mysite.views',
    # Example:
    # (r'^mysite/', include('mysite.foo.urls')),
    (r'^$','index'),
    (r'^hello/$','hello'),
    (r'^time/$','current_datetime'),
    (r'^time/now_in_london/$','now_in_london'),
    (r'^time/plus/(-?\d{1,2})/$', 'hours_ahead'),
    (r'^checkbrowser/$','checkbrowser'),
    (r'^displaymeta/$','display_meta'),
    (r'^foo/$','foo_view'),
    (r'^bar/$','bar_view'),
    (r'^say_hello/([\w\W]*)/$','say_hello'),
    (r'^say_goodbye/([\w\W]*)/$','say_goodbye'),
    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
     (r'^admin/(.*)', admin.site.root),
)
urlpatterns+=patterns('mysite.books.views',
    (r'^search/$','search'),
    (r'^search_form/$','search_form'),
    (r'^contact/$','contact'),
    (r'^contact_form/$','contact_form'),
)
from django.views.generic.simple import direct_to_template
from mysite.books.views import about_pages
urlpatterns += patterns('',
    ('^about/$', direct_to_template, {
        'template': 'about.html'
    }),
    ('^about/(w+)/$',about_pages),
)

from django.views.generic import list_detail
from mysite.books.models import Publisher
from mysite.books.models import Book
def get_books():
    return Book.objects.all()
publisher_info = {
    "queryset" : Publisher.objects.all(),
    "template_object_name" : "publisher",
    "extra_context":{"book_list":get_books},
    "extra_context":{"book_list":Book.objects.all}
    #"extra_context":{"book_list":Book.objects.all()},
}
urlpatterns += patterns('',
    (r'^publishers/$', list_detail.object_list, publisher_info),
)

book_info={
    "queryset":Book.objects.all().order_by("-publication_date"),
    "template_object_name":"book",
}
urlpatterns+=patterns('',
    (r'^books/$',list_detail.object_list,book_info)
)
from mysite.books.models import Author
author_info={
    "queryset":Author.objects.all(),
    "template_object_name":"author",
}
urlpatterns+=patterns('',
    (r'^authors/$',list_detail.object_list,author_info)
)
OReilly_books={
    "queryset":Book.objects.filter(publisher__name="O'Reilly"),
    "template_object_name":"book",
    "template_name":"books/OReilly_list.html",
}
urlpatterns+=patterns('',
    (r'^books/OReilly/$',list_detail.object_list,OReilly_books),
)

urlpatterns+=patterns('mysite.books.views',
    (r'^books/(\w+)/$','books_by_publisher'),                      
)
from mysite.books.views import author_detail
urlpatterns+=patterns('',
    (r'^authors/(?P<author_id>d+)/$', author_detail),
)
urlpatterns+=patterns('mysite.books.views',
    (r'^author_list_plaintext/$','author_list_plaintext')
)

learning/djangoLearning/mysite/books/forms.py
from django import forms
from models import Publisher
from django.forms import ModelForm

TOPIC_CHOICES = (
    ('general', 'General enquiry'),
    ('bug', 'Bug report'),
    ('suggestion', 'Suggestion'),
)

class ContactForm(forms.Form):
    topic = forms.ChoiceField(choices=TOPIC_CHOICES)
    message = forms.CharField(widget=forms.Textarea(),
                              initial="Repalce with your feddback")
    sender = forms.EmailField(required=False)
    def clean_message(self):
        message=self.cleaned_data.get('message','')
        num_words=len(message.split())
        if num_words<4:
            raise forms.ValidationError("Not enough words!")
        return message

learning/djangoLearning/mysite/templates/about.html
<HTML>
	<HEAD><TITLE>关于我们</TITLE></HEAD>
	<BODY>
		<H1>关于我们</H1>
	</BODY>
</HTML>

learning/djangoLearning/mysite/templates/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html>
	<head>
	    <title>{% block title %}{% endblock %}</title>
	</head>
	<body>
	    <h1>我的站点</h1>
	    {% block content %}{% endblock %}
	    {% block footer %}
	    <hr>
	    <p>非常感谢您的访问！</p>
	    {% endblock %}
	</body>
</html>

learning/djangoLearning/mysite/templates/contact.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">
	<head>
		<title>Contact us</title>
	</head>
	<body>
		<h1>Contact us</h1>
		<form action="." method="POST">
			<div class="fieldWrapper">
				{{ form.topic.errors }}
				<label for="id_topic">Kind of feedback:</label>
				{{ form.topic }}
			</div>
			<div class="filedWrapper{% if form.message.errors %}errors{% endif %}">			
				{% if form.message.errors %}
					<ol>
						{% for error in form.message.errors %}
							<li>
								<strong>{{ error|escape }}</strong>
							</li>
						{% endfor %}
					</ol>
				{% endif %}
				{{ form.message }}
			</div>
			<div class="filedWrapper">
				{{ form.sender.errors }}
				<label for="id_sender">Your email(optional):</label>
				{{ form.sender }}
			</div>
			<p><input type="submit" value="Submit"></p>
		</form>
	</body>
</html>

<style type="text/css">
	ul.errorlist{
		margin:0;
		padding:0;
	}
	.errorlist li{
		backgrount-color:red;
		color:white;
		display:block;
		font-size:10px;
		margin:0 0 3px;
		padding:4px 5px;
	}
</style>

learning/djangoLearning/mysite/templates/contact_form.html
<html>
	<head>
		<title>联系我们</title>
	</head>
	<body>
		<h1>联系我们</h1>
		{% if errors %}
			<ul>	
				{% for error in errors %}
					<li>{{ error }}</li>
				{% endfor %}
			</ul>
		{% endif %}
		<form action="/contact/" method="post">
			<p>主题：<input type="text" name="subject"></p>
			<p>邮件地址（可选）：<input type="text" name="email"></p>
			<p>信息：<textarea name="message" row="10" cols="50"></textarea></p>
			<input type="submit" value="提交">
		</form>
	</body>
</html>

learning/djangoLearning/mysite/templates/current_datetime.html
{% extends "base.html" %}

{% block title %}当前时间{% endblock %}

{% block content %}
<p>当前时间为： {{ current_date }}.</p>
{% endblock %}

learning/djangoLearning/mysite/templates/hours_ahead.html
{% extends "base.html" %}

{% block title %}将来时间{% endblock %}

{% block content %}
<p>在{{ hour_offset }} 个小时后的时间为：{{ next_time }}.</p>
{% endblock %}

learning/djangoLearning/mysite/templates/index.html
{% extends "base.html" %}

{% block title %}主页{% endblock %}

{% block content %}
<p>主页</p>
<a href="hello">hello</a>
<a href="time">time</a>
<a href="time/now_in_london">time/now_in_london</a>
<a href="time/plus/1">time/plus/1</a>
<a href="checkbrowser">checkbrowser</a>
<a href="foo">foo</a>
<a href="bar">bar</a>
<a href="say_hello/crackpot">say_hello/crackpot</a>
<a href="admin">admin</a>
{% endblock %}